### ISSUE TITLE
Thanks! for the making of this repo

### ISSUE THREAD

**Issue by loneicewolf** [redskal/obfuscatxor#1]
Hello!
It was awhile ago I browsed some obfuscation repos and, this one got recommend in my feed I think.. Or how I saw it I am not sure; but anyway - I always make a issue on projects I **find helpful and useful**, as I will begin coding GO soon.

**Comment by redskal** [comment]
I'm glad you've found it useful. As you may be able to tell, it's not intended to be a deployable solution as-is; it's meant as a building block for customisation and implementing some more robust obfuscation.

Enjoy your adventures into Golang!
